"""Generate 20 structured career knowledge-base JSON files. Run: python scripts/generate_kb.py"""
import json
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent / "knowledge_base"

KB = {
"Data Analyst": dict(
 description="Analyzes datasets to produce insights, dashboards, and reports that guide business decisions.",
 responsibilities=["Collect and clean data with SQL/Python","Build dashboards (Power BI/Tableau)","Perform exploratory analysis and KPI reporting","Present findings to stakeholders"],
 prerequisites=["Bachelor's degree (any quantitative field)","SQL and spreadsheets","Basic statistics"],
 required_skills=["SQL","Excel","Data Visualization","Statistics","Python (Pandas)"], preferred_skills=["Power BI","Tableau","A/B testing","Business storytelling"],
 programming_languages=["SQL","Python"], technologies=["Pandas","Excel","Power BI","Tableau","PostgreSQL"],
 tools=["Jupyter","Power BI","Tableau","Looker","Git"],
 certifications=["Google Data Analytics Professional Certificate","Microsoft PL-300 (Power BI)","IBM Data Analyst"],
 beginner_skills=["SQL basics","Excel","Descriptive statistics"], intermediate_skills=["Pandas","Dashboard design","Data modeling basics"],
 advanced_skills=["Advanced visualization","Experiment analysis","Stakeholder communication"],
 projects=["Sales dashboard in Power BI","Customer churn EDA","KPI automation with Python"],
 career_progression=["Data Analyst Intern","Junior Data Analyst","Data Analyst","Senior Data Analyst","Analytics Manager"],
 related_roles=["Business Analyst","Data Scientist","Data Engineer"],
 learning_resources=["Google Data Analytics (Coursera)","Mode SQL tutorial","Storytelling with Data (book)"]),
"Data Scientist": dict(
 description="Builds statistical and ML models to predict outcomes and drive product and business strategy.",
 responsibilities=["Frame business problems as ML/statistical tasks","Feature engineering and model training","Evaluate and deploy models","Communicate insights"],
 prerequisites=["Python, statistics, SQL","Bachelor's/Master's in quantitative field"],
 required_skills=["Python","SQL","Statistics","Machine Learning","Data Visualization"], preferred_skills=["Deep Learning basics","Experimentation","MLOps basics"],
 programming_languages=["Python","SQL","R (optional)"], technologies=["Pandas","NumPy","Scikit-learn","Jupyter","Power BI"],
 tools=["Jupyter","MLflow","Git","Docker (basic)","Tableau"],
 certifications=["IBM Data Science Professional","Google Advanced Data Analytics","AWS ML Specialty (later)"],
 beginner_skills=["Python","SQL","Statistics"], intermediate_skills=["Regression/Classification","Scikit-learn","Feature engineering"],
 advanced_skills=["Model deployment","Experiment design","ML system design basics"],
 projects=["House-price prediction system","Customer churn classifier","NLP sentiment dashboard"],
 career_progression=["Data Analyst","Junior Data Scientist","Data Scientist","Senior Data Scientist","ML Lead"],
 related_roles=["Machine Learning Engineer","Data Analyst","AI Engineer"],
 learning_resources=["Andrew Ng ML Specialization","Hands-On ML (Geron)","Kaggle Learn"]),
"Machine Learning Engineer": dict(
 description="Designs, trains, and deploys ML systems to production at scale.",
 responsibilities=["Build training/serving pipelines","Model optimization and monitoring","Deploy with Docker/K8s and cloud","Collaborate with data scientists"],
 prerequisites=["Strong Python and ML fundamentals","Math: linear algebra, probability"],
 required_skills=["Python","Scikit-learn","PyTorch/TensorFlow","MLOps","SQL"], preferred_skills=["Kubernetes","Spark","LLM fine-tuning"],
 programming_languages=["Python","SQL"], technologies=["PyTorch","TensorFlow","Scikit-learn","MLflow","Docker","Kubernetes"],
 tools=["MLflow","Docker","Kubernetes","Weights & Biases","Git"],
 certifications=["AWS Certified Machine Learning Specialty","Google Professional ML Engineer","TensorFlow Developer Certificate"],
 beginner_skills=["Python","Scikit-learn","Statistics"], intermediate_skills=["Deep learning","APIs (FastAPI)","Docker"],
 advanced_skills=["Distributed training","Model monitoring","LLMOps"],
 projects=["Image classifier API with FastAPI","Recommendation engine","MLOps pipeline on cloud"],
 career_progression=["Junior ML Engineer","ML Engineer","Senior ML Engineer","ML Architect","ML Lead"],
 related_roles=["Data Scientist","AI Engineer","Data Engineer"],
 learning_resources=["DeepLearning.AI MLOps","Full Stack Deep Learning","Made With ML"]),
"AI Engineer": dict(
 description="Builds LLM-powered applications using RAG, agents, embeddings, and vector databases.",
 responsibilities=["Design RAG pipelines (chunking, embeddings, retrieval)","Prompt engineering and evaluation","Build agents and tool use","Deploy LLM apps"],
 prerequisites=["Python, APIs, basic ML","Familiarity with LLMs"],
 required_skills=["Python","LLMs","RAG","Prompt Engineering","Vector Databases"], preferred_skills=["LangChain","Evaluation (RAGAS)","Cloud deployment"],
 programming_languages=["Python","TypeScript (basic)"], technologies=["LangChain","OpenAI API","FAISS","ChromaDB","FastAPI"],
 tools=["LangChain/LlamaIndex","ChromaDB","Docker","Git","Hugging Face"],
 certifications=["DeepLearning.AI LangChain / GenAI courses","AWS AI Practitioner","Azure AI Engineer Associate"],
 beginner_skills=["Python","APIs","Embeddings basics"], intermediate_skills=["RAG","Prompt patterns","Vector search"],
 advanced_skills=["Agents","Evals and guardrails","Production LLM systems"],
 projects=["Career RAG chatbot","PDF Q&A with citations","AI agent with tools"],
 career_progression=["AI Engineer Intern","AI Engineer","Senior AI Engineer","GenAI Architect"],
 related_roles=["Machine Learning Engineer","Full Stack Developer","Data Scientist"],
 learning_resources=["DeepLearning.AI GenAI short courses","LangChain docs","RAG papers (Lewis et al.)"]),
"Software Developer": dict(
 description="Generalist developer building applications, features, and maintaining codebases.",
 responsibilities=["Write clean tested code","Debug and review code","Work in Agile teams","Maintain docs"],
 prerequisites=["Programming fundamentals + DSA basics"],
 required_skills=["Python/Java","Git","DSA basics","OOP","Debugging"], preferred_skills=["Databases","APIs","Testing"],
 programming_languages=["Python","Java"], technologies=["Git","REST APIs","PostgreSQL","Linux"],
 tools=["VS Code","Git","Jira","Docker (basic)"],
 certifications=["Oracle Java Foundations","Meta Programming with JavaScript","AWS Cloud Practitioner"],
 beginner_skills=["Programming basics","Git","OOP"], intermediate_skills=["DSA","Databases","Testing"],
 advanced_skills=["System design basics","CI/CD","Performance tuning"],
 projects=["To-do app with DB","REST API project","Open-source contribution"],
 career_progression=["Intern","Junior Developer","Software Developer","Senior Developer","Tech Lead"],
 related_roles=["Backend Developer","QA Engineer","Mobile App Developer"],
 learning_resources=["CS50","LeetCode Easy","The Odin Project"]),
"Full Stack Developer": dict(
 description="Builds end-to-end web apps: frontend UI plus backend APIs and databases.",
 responsibilities=["Build React frontends","Design REST APIs","Model databases","Deploy apps"],
 prerequisites=["HTML/CSS/JS plus one backend language"],
 required_skills=["JavaScript","React","Node.js","SQL","REST APIs"], preferred_skills=["TypeScript","Docker","Cloud deploy"],
 programming_languages=["JavaScript","TypeScript","Python/Node"], technologies=["React","Node.js","Express","PostgreSQL","MongoDB"],
 tools=["VS Code","Git","Docker","Vercel","Postman"],
 certifications=["Meta Front-End + Back-End Professional","AWS Developer Associate"],
 beginner_skills=["HTML/CSS/JS","React basics","SQL basics"], intermediate_skills=["Auth","State management","API design"],
 advanced_skills=["System design","Caching","CI/CD"],
 projects=["E-commerce full-stack app","Blog with auth","SaaS dashboard"],
 career_progression=["Frontend/Backend Dev","Full Stack Developer","Senior Full Stack","Engineering Manager"],
 related_roles=["Frontend Developer","Backend Developer","DevOps Engineer"],
 learning_resources=["freeCodeCamp Full Stack","Epic React","Full Stack Open"]),
"Backend Developer": dict(
 description="Builds server-side logic, APIs, databases, and integrations.",
 responsibilities=["Design APIs and schemas","Auth and caching","Optimize queries","Ensure reliability"],
 prerequisites=["One backend language + SQL"],
 required_skills=["Python/Java/Node","REST APIs","SQL","Auth","Caching"], preferred_skills=["Kafka","Microservices","K8s basics"],
 programming_languages=["Python","Java","Go (optional)"], technologies=["Django/FastAPI","Spring/Express","PostgreSQL","Redis"],
 tools=["Postman","Docker","Git","Linux","Nginx"],
 certifications=["AWS Developer Associate","Oracle Java Professional","MongoDB Developer"],
 beginner_skills=["Backend language","SQL","REST"], intermediate_skills=["Auth/JWT","ORMs","Testing"],
 advanced_skills=["Microservices","Message queues","System design"],
 projects=["REST API with auth","URL shortener","Payment integration"],
 career_progression=["Junior Backend","Backend Developer","Senior Backend","Backend Architect"],
 related_roles=["Full Stack Developer","DevOps Engineer","Database Administrator"],
 learning_resources=["Django/Node docs","Designing Data-Intensive Applications","Backend roadmap.sh"]),
"Frontend Developer": dict(
 description="Builds responsive, accessible user interfaces for web apps.",
 responsibilities=["Implement UI from designs","State management","Performance optimization","Accessibility"],
 prerequisites=["HTML, CSS, JavaScript"],
 required_skills=["HTML/CSS","JavaScript","React","Responsive Design","Git"], preferred_skills=["TypeScript","Next.js","Testing"],
 programming_languages=["JavaScript","TypeScript"], technologies=["React","Next.js","Tailwind CSS","Vite"],
 tools=["VS Code","Figma","Chrome DevTools","Git"],
 certifications=["Meta Front-End Developer Professional","JavaScript Algorithms (freeCodeCamp)"],
 beginner_skills=["HTML/CSS","JS basics","React basics"], intermediate_skills=["Hooks","Routing","API integration"],
 advanced_skills=["Performance","Testing","Design systems"],
 projects=["Portfolio site","E-commerce UI","Dashboard UI"],
 career_progression=["Junior Frontend","Frontend Developer","Senior Frontend","UI Architect"],
 related_roles=["UI/UX Designer","Full Stack Developer","Mobile App Developer"],
 learning_resources=["Epic React","Frontend Masters","web.dev"]),
"Cloud Engineer": dict(
 description="Designs and operates cloud infrastructure (AWS/Azure/GCP) for scalable apps.",
 responsibilities=["Provision infra with IaC","Manage networking and IAM","Cost optimization","Monitoring"],
 prerequisites=["Linux, networking basics, one cloud"],
 required_skills=["AWS/Azure","Linux","Networking","Terraform","Docker"], preferred_skills=["Kubernetes","CI/CD","Python scripting"],
 programming_languages=["Python","Bash"], technologies=["AWS","Terraform","Docker","Linux","CloudWatch"],
 tools=["AWS Console","Terraform","Docker","GitHub Actions"],
 certifications=["AWS Solutions Architect Associate","AZ-104 Azure Administrator","Google Associate Cloud Engineer"],
 beginner_skills=["Linux","Cloud basics","Networking"], intermediate_skills=["IaC","IAM","Containers"],
 advanced_skills=["Multi-cloud design","Cost governance","SRE basics"],
 projects=["3-tier app on AWS","Terraform VPC module","Static site + CDN"],
 career_progression=["Cloud Support","Cloud Engineer","Senior Cloud Engineer","Cloud Architect"],
 related_roles=["DevOps Engineer","Network Engineer","Backend Developer"],
 learning_resources=["AWS Skill Builder","A Cloud Guru","Terraform docs"]),
"DevOps Engineer": dict(
 description="Automates build, test, and deployment pipelines and manages production reliability.",
 responsibilities=["Build CI/CD pipelines","Container orchestration","Infra as code","Incident response"],
 prerequisites=["Linux, Git, scripting, cloud basics"],
 required_skills=["Linux","Docker","Kubernetes","CI/CD","Cloud"], preferred_skills=["Terraform","Monitoring","Python"],
 programming_languages=["Python","Bash"], technologies=["Docker","Kubernetes","Jenkins/GitHub Actions","Terraform","Prometheus"],
 tools=["Docker","Kubernetes","ArgoCD","Grafana","Git"],
 certifications=["CKA (Kubernetes)","AWS DevOps Engineer Professional","Docker Certified Associate"],
 beginner_skills=["Linux","Git","Docker basics"], intermediate_skills=["CI/CD","K8s basics","IaC"],
 advanced_skills=["GitOps","Observability","SRE practices"],
 projects=["CI/CD for a web app","K8s deployment","Monitoring stack"],
 career_progression=["Junior DevOps","DevOps Engineer","Senior DevOps","SRE/Platform Lead"],
 related_roles=["Cloud Engineer","Backend Developer","QA Engineer"],
 learning_resources=["KodeKloud","DevOps roadmap.sh","Google SRE book"]),
"Cybersecurity Analyst": dict(
 description="Monitors threats, triages alerts, and strengthens security posture (SOC).",
 responsibilities=["Monitor SIEM alerts","Incident triage","Vulnerability assessment","Security awareness"],
 prerequisites=["Networking + Linux basics"],
 required_skills=["Networking","Linux","SIEM","Incident Response","Security Basics"], preferred_skills=["Python scripting","Threat intel","Cloud security"],
 programming_languages=["Python","Bash"], technologies=["Splunk/Wazuh","Wireshark","Nmap","Linux"],
 tools=["Splunk","Wireshark","Burp Suite (basic)","VirusTotal"],
 certifications=["CompTIA Security+","SC-900","Google Cybersecurity Certificate"],
 beginner_skills=["Networking","Linux","Security concepts"], intermediate_skills=["SIEM","Vuln scanning","Log analysis"],
 advanced_skills=["Threat hunting","DFIR basics","Purple teaming"],
 projects=["Home SOC lab","Phishing analysis","Vuln assessment report"],
 career_progression=["SOC Analyst L1","Cybersecurity Analyst","Senior Analyst","Security Engineer"],
 related_roles=["Cybersecurity Engineer","Network Engineer","Cloud Engineer"],
 learning_resources=["TryHackMe SOC paths","Blue Team Field Manual","Professor Messer Security+"]),
"Cybersecurity Engineer": dict(
 description="Designs and implements security controls: hardening, pentesting, secure architecture.",
 responsibilities=["Harden systems and cloud","Pentesting basics","Automate security","Design secure networks"],
 prerequisites=["Networking, Linux, scripting; Security+ helpful"],
 required_skills=["Network Security","Linux Hardening","Pentesting","Python","Cloud Security"], preferred_skills=["K8s security","DFIR","DevSecOps"],
 programming_languages=["Python","Bash"], technologies=["Burp Suite","Metasploit","Nmap","AWS Security","Docker"],
 tools=["Burp Suite","Metasploit","Nessus","BloodHound"],
 certifications=["CompTIA Security+/CySA+","CEH","OSCP (advanced)","CISSP (experienced)"],
 beginner_skills=["Networking","Linux","Web security basics"], intermediate_skills=["Pentest methodology","Cloud IAM","Scripting"],
 advanced_skills=["Exploit dev basics","Red team ops","Security architecture"],
 projects=["Pentest lab writeups","Secure cloud baseline","SAST in CI pipeline"],
 career_progression=["Security Analyst","Security Engineer","Senior Security Engineer","Security Architect"],
 related_roles=["Cybersecurity Analyst","Network Engineer","DevOps Engineer"],
 learning_resources=["HackTheBox","PortSwigger Academy","OWASP guides"]),
"Database Administrator": dict(
 description="Administers databases: performance, backups, HA, and security.",
 responsibilities=["Install/tune databases","Backups and recovery","HA/replication","Access control"],
 prerequisites=["SQL strong; Linux basics"],
 required_skills=["SQL","PostgreSQL/MySQL","Backups","Performance Tuning","Linux"], preferred_skills=["MongoDB","Cloud RDS","Shell scripting"],
 programming_languages=["SQL","Bash","Python (basic)"], technologies=["PostgreSQL","MySQL","MongoDB","Redis"],
 tools=["pgAdmin","MySQL Workbench","Percona","Grafana"],
 certifications=["Oracle Database Admin","PostgreSQL Associate","AWS Database Specialty"],
 beginner_skills=["SQL","DB concepts","Linux basics"], intermediate_skills=["Indexing","Backups","Replication"],
 advanced_skills=["HA design","Sharding","Disaster recovery"],
 projects=["Tuned slow queries","Backup automation","HA replica setup"],
 career_progression=["DB Support","DBA","Senior DBA","Data Architect"],
 related_roles=["Data Engineer","Backend Developer","Cloud Engineer"],
 learning_resources=["PostgreSQL docs","Use The Index Luke","DBA StackExchange"]),
"Data Engineer": dict(
 description="Builds data pipelines and warehouses that feed analytics and ML.",
 responsibilities=["Build ETL/ELT pipelines","Model warehouses","Orchestrate with Airflow","Ensure data quality"],
 prerequisites=["SQL + Python; cloud basics"],
 required_skills=["SQL","Python","ETL","Airflow","Spark basics"], preferred_skills=["dbt","Kafka","Cloud warehouses"],
 programming_languages=["Python","SQL"], technologies=["Airflow","Spark","dbt","Snowflake/BigQuery","Kafka"],
 tools=["Airflow","Docker","dbt","Git","Great Expectations"],
 certifications=["Google Professional Data Engineer","AWS Data Engineer Associate","Databricks Data Engineer"],
 beginner_skills=["SQL","Python","ETL basics"], intermediate_skills=["Orchestration","Warehouse modeling","Streaming basics"],
 advanced_skills=["Lakehouse design","Data contracts","Cost/perf tuning"],
 projects=["Batch ETL pipeline","Streaming pipeline","dbt warehouse project"],
 career_progression=["Junior Data Engineer","Data Engineer","Senior Data Engineer","Data Architect"],
 related_roles=["Data Analyst","Database Administrator","ML Engineer"],
 learning_resources=["Data Engineering Zoomcamp","Kimball modeling","Spark docs"]),
"Business Analyst": dict(
 description="Bridges business and tech: requirements, process analysis, and data-driven recommendations.",
 responsibilities=["Gather requirements","Process mapping","Stakeholder communication","Basic data analysis"],
 prerequisites=["Communication + Excel/SQL basics"],
 required_skills=["Communication","Requirements","SQL basics","Excel","Process Modeling"], preferred_skills=["Power BI","Agile","Domain knowledge"],
 programming_languages=["SQL"], technologies=["Excel","Jira","Power BI","Confluence","BPMN tools"],
 tools=["Jira","Confluence","Excel","Lucidchart"],
 certifications=["ECBA/CBAP (IIBA)","Agile (PSM I)","Google Data Analytics"],
 beginner_skills=["Excel","Documentation","BPMN basics"], intermediate_skills=["SQL","Dashboards","User stories"],
 advanced_skills=["Product analytics","Stakeholder mgmt","Strategy"],
 projects=["BRD for a feature","Process improvement case","Dashboard for KPIs"],
 career_progression=["BA Intern","Business Analyst","Senior BA","Product Manager"],
 related_roles=["Data Analyst","QA Engineer","UI/UX Designer"],
 learning_resources=["IIBA BABOK guide","Agile PM (Coursera)","HBR cases"]),
"UI/UX Designer": dict(
 description="Designs intuitive interfaces and experiences via research, wireframes, and prototypes.",
 responsibilities=["User research","Wireframes and prototypes","Usability testing","Design systems"],
 prerequisites=["Design sense + Figma basics"],
 required_skills=["Figma","User Research","Wireframing","Prototyping","Visual Design"], preferred_skills=["HTML/CSS basics","Motion","Accessibility"],
 programming_languages=["HTML/CSS (basic)","JavaScript (basic)"], technologies=["Figma","FigJam","Maze","Notion"],
 tools=["Figma","Miro","Maze","Zeplin"],
 certifications=["Google UX Design Professional","NN/g UX Certification","Adobe Certified"],
 beginner_skills=["Design basics","Figma","Typography"], intermediate_skills=["Research","Prototyping","Design systems"],
 advanced_skills=["UX strategy","Advanced testing","Leadership"],
 projects=["Mobile app redesign","Design system","Usability study"],
 career_progression=["Design Intern","UI/UX Designer","Senior Designer","Design Lead"],
 related_roles=["Frontend Developer","Business Analyst","Mobile App Developer"],
 learning_resources=["Google UX (Coursera)","Refactoring UI","Laws of UX"]),
"Mobile App Developer": dict(
 description="Builds native/cross-platform mobile apps (Flutter/React Native/Android/iOS).",
 responsibilities=["Build mobile UIs","Integrate APIs","Publish to stores","Optimize performance"],
 prerequisites=["OOP + one mobile framework"],
 required_skills=["Flutter/React Native","Dart/Kotlin/Swift basics","REST APIs","Git","App Store Release"], preferred_skills=["Firebase","Native modules","CI/CD for mobile"],
 programming_languages=["Dart","Kotlin","Swift","JavaScript"], technologies=["Flutter","React Native","Firebase","SQLite"],
 tools=["Android Studio","Xcode","VS Code","Firebase Console"],
 certifications=["Google Associate Android Developer","Meta React Native","Flutter (Udemy/official)"],
 beginner_skills=["OOP","Mobile basics","APIs"], intermediate_skills=["State mgmt","Firebase","Publishing"],
 advanced_skills=["Native bridges","Performance","Modular architecture"],
 projects=["Notes app","E-commerce app","Chat app with Firebase"],
 career_progression=["Junior Mobile Dev","Mobile Developer","Senior Mobile Dev","Mobile Lead"],
 related_roles=["Frontend Developer","Full Stack Developer","UI/UX Designer"],
 learning_resources=["Flutter docs","Android Basics (Google)","React Native docs"]),
"QA Engineer": dict(
 description="Ensures quality via manual and automated testing across the SDLC.",
 responsibilities=["Write test plans","Automate with Selenium/Playwright","API testing","Bug reporting"],
 prerequisites=["SDLC basics + scripting"],
 required_skills=["Manual Testing","Selenium/Playwright","API Testing","SQL basics","Git"], preferred_skills=["Performance testing","CI integration","Python/Java"],
 programming_languages=["Python","Java","JavaScript"], technologies=["Selenium","Playwright","Postman","Jenkins"],
 tools=["Jira","TestRail","Postman","Selenium Grid"],
 certifications=["ISTQB Foundation","Selenium WebDriver (Udemy)","Postman API Testing"],
 beginner_skills=["Testing basics","SQL","Git"], intermediate_skills=["Automation","API tests","CI tests"],
 advanced_skills=["Framework design","Performance/security testing","QA leadership"],
 projects=["Automation suite","API test collection","Bug bash report"],
 career_progression=["QA Intern","QA Engineer","Senior QA / SDET","QA Lead"],
 related_roles=["Software Developer","Business Analyst","DevOps Engineer"],
 learning_resources=["ISTQB syllabus","Guru99","Test Automation University"]),
"Network Engineer": dict(
 description="Designs and operates networks: routing, switching, firewalls, and cloud connectivity.",
 responsibilities=["Configure routers/switches","Manage firewalls/VPN","Monitor performance","Troubleshoot"],
 prerequisites=["TCP/IP + CCNA-level knowledge"],
 required_skills=["TCP/IP","Routing/Switching","Firewalls","VPN","Linux basics"], preferred_skills=["Cloud networking","Automation (Ansible)","Security"],
 programming_languages=["Python (basic)","Bash"], technologies=["Cisco","Fortinet","Wireshark","AWS VPC"],
 tools=["Wireshark","gns3/EVE-NG","Ansible","SolarWinds"],
 certifications=["CCNA","CompTIA Network+","AWS Advanced Networking"],
 beginner_skills=["OSI/TCP-IP","Subnetting","CLI basics"], intermediate_skills=["Routing protocols","Firewalls","VPNs"],
 advanced_skills=["SD-WAN","Automation","Network security design"],
 projects=["Home lab network","Site-to-site VPN","Monitoring setup"],
 career_progression=["NOC Engineer","Network Engineer","Senior Network Engineer","Network Architect"],
 related_roles=["Cloud Engineer","Cybersecurity Engineer","DevOps Engineer"],
 learning_resources=["Jeremy's IT Lab (CCNA)","Cisco NetAcad","NetworkLessons"]),
"Embedded Systems Engineer": dict(
 description="Builds firmware and embedded systems with C/C++ on microcontrollers and RTOS.",
 responsibilities=["Write C/C++ firmware","Interface sensors/actuators","RTOS tasks","Debug with oscilloscope/JTAG"],
 prerequisites=["C/C++ + electronics basics"],
 required_skills=["C","C++","Microcontrollers","RTOS","Electronics basics"], preferred_skills=["Python tooling","ROS","IoT protocols"],
 programming_languages=["C","C++","Python (tooling)"], technologies=["STM32/ESP32","FreeRTOS","Arduino","MQTT"],
 tools=["PlatformIO","Keil","Oscilloscope","Git","Logic analyzer"],
 certifications=["Embedded Systems (Coursera/UCI)","ARM Accredited Engineer","IPC basics"],
 beginner_skills=["C","Arduino","Circuits basics"], intermediate_skills=["RTOS","Peripherals (I2C/SPI/UART)","PCB basics"],
 advanced_skills=["Bare-metal drivers","Low-power design","ROS/robotics"],
 projects=["Weather station (ESP32)","Line-follower robot","RTOS sensor hub"],
 career_progression=["Embedded Intern","Embedded Engineer","Senior Embedded Engineer","Firmware Architect"],
 related_roles=["Network Engineer","Mobile App Developer","QA Engineer"],
 learning_resources=["Embedded.fm","FastBit Academy","STM32 docs"]),
}

def main():
    BASE.mkdir(parents=True, exist_ok=True)
    for role, d in KB.items():
        doc = {"career_role": role, **d}
        fname = role.lower().replace("/", "_").replace(" ", "_") + ".json"
        with open(BASE / fname, "w", encoding="utf-8") as f:
            json.dump(doc, f, indent=2, ensure_ascii=False)
    print(f"Wrote {len(KB)} KB docs -> {BASE}")

if __name__ == "__main__":
    main()
